### ISSUE TITLE
FBC measures test failure on PPC

### ISSUE THREAD

**Issue by matthew-brett** [dipy/dipy#1264]
Power PPC test seems to be a fair bit off expected...

```
======================================================================
FAIL: Test the FBC measures on a set of fibers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildslave/debian-ppc-64/dipy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/buildslave/debian-ppc-64/dipy-py2_7-debian-ppc/build/venv/local/lib/python2.7/site-packages/dipy/tracking/tests/test_fbc.py", line 48, in test_fbc
    npt.assert_almost_equal(np.mean(rfbc_orig), 1.0500466494329224)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 470, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 7 decimals
 ACTUAL: 1.0441612052589981
 DESIRED: 1.0500466494329224
```

https://nipy.bic.berkeley.edu/builders/dipy-py2.7-debian-ppc/builds/220/steps/shell_9/logs/stdio

Last passing revision was e414987749bd50a203ab2a0e3764f0d1bbeda580 on Jan 9th - see https://nipy.bic.berkeley.edu/builders/dipy-py2.7-debian-ppc

**Comment by arokem** [comment]
Might this be related somehow to pytables? 

The commit that seems to have broken this was this one: https://github.com/nipy/dipy/commit/147d20737d450cb17e0a6045475eb3b10df725ed

**Comment by skoudoro** [comment]
issue on python27 and not anymore relevant. closing
