### ISSUE TITLE
test_mapmri_isotropic_static_scale_factor failure on OSX buildbot

### ISSUE THREAD

**Issue by matthew-brett** [dipy/dipy#1266]
```
======================================================================
FAIL: dipy.reconst.tests.test_mapmri.test_mapmri_isotropic_static_scale_factor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/buildslave/osx-10.7/dipy-py2_7-osx-10_7/build/venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/buildslave/osx-10.7/dipy-py2_7-osx-10_7/build/venv/lib/python2.7/site-packages/dipy/reconst/tests/test_mapmri.py", line 294, in test_mapmri_isotropic_static_scale_factor
    True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 334, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: False
 DESIRED: True
```

https://nipy.bic.berkeley.edu/builders/dipy-py2.7-osx-10.7/builds/542/steps/shell_9/logs/stdio

Can give login access to the machine if needed.

**Comment by matthew-brett** [comment]
Same failure on a Windows buildbot : https://nipy.bic.berkeley.edu/builders/dipy-bdist64-35-win2016/builds/80/steps/shell_12/logs/stdio

**Comment by Garyfallidis** [comment]
Could it be that you do not have cvxopt installed in those machines?

**Comment by matthew-brett** [comment]
You can always see what's installed on the buildbot runs, because we run a `pip freeze` before we run the tests:  https://nipy.bic.berkeley.edu/builders/dipy-bdist64-35-win2016/builds/80/steps/shell_8/logs/stdio

No cvxopt on that machine.  Maybe the test needs to be skipped or adapted to the not-cvxopt case.

**Comment by Garyfallidis** [comment]
Hi Matthew, this error stopped appearing both in the buildbot and our local machines. Not sure why. We ran the tests multiple times. Nothing so far.

**Comment by matthew-brett** [comment]
Back again!  This time on Windows, building 0.13.0:

```
======================================================================
FAIL: dipy.reconst.tests.test_mapmri.test_mapmri_isotropic_static_scale_factor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python35-x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\python35-x64\lib\site-packages\dipy\reconst\tests\test_mapmri.py", line 292, in test_mapmri_isotropic_static_scale_factor
    True)
  File "c:\python35-x64\lib\site-packages\numpy\testing\utils.py", line 355, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: False
 DESIRED: True
```

https://ci.appveyor.com/project/matthew-brett/dipy-wheels/build/1.0.10/job/ljvp4ei51oylwfjh#L4164

The failure is not deterministic - the same code passed in the previous run : https://ci.appveyor.com/project/matthew-brett/dipy-wheels/build/1.0.6/job/or79479lk72a897j

**Comment by skoudoro** [comment]
We do not have anymore this problem. The test has changed to be more robust/deterministic. Closing
