### ISSUE TITLE
Failure on Windows/Python 3.5

### ISSUE THREAD

**Issue by arokem** [dipy/dipy#1724]
Also observed on #1230 

https://ci.appveyor.com/project/arokem/dipy/builds/21758900/job/udxs3itstqxllod4

```
======================================================================
ERROR: dipy.workflows.tests.test_tracking.test_det_track
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python35-x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\projects\dipy\dipy\workflows\tests\test_tracking.py", line 45, in test_det_track
    det_track_pam.run(pam_path, gfa_path, seeds_path)
  File "c:\projects\dipy\dipy\workflows\tracking.py", line 106, in run
    seed_density, use_sh, pam, out_tract)
  File "c:\projects\dipy\dipy\workflows\tracking.py", line 45, in _core_run
    tractogram = Tractogram(streamlines, affine_to_rasmm=np.eye(4))
  File "c:\python35-x64\lib\site-packages\nibabel\streamlines\tractogram.py", line 328, in __init__
    self._set_streamlines(streamlines)
  File "c:\python35-x64\lib\site-packages\nibabel\streamlines\tractogram.py", line 338, in _set_streamlines
    self._streamlines = ArraySequence(value)
  File "c:\python35-x64\lib\site-packages\nibabel\streamlines\array_sequence.py", line 93, in __init__
    self.extend(iterable)
  File "c:\python35-x64\lib\site-packages\nibabel\streamlines\array_sequence.py", line 239, in extend
    for e in elements:
  File "c:\projects\dipy\dipy\tracking\utils.py", line 958, in move_streamlines
    for sl in streamlines:
  File "c:\projects\dipy\dipy\tracking\local\localtracking.py", line 131, in _generate_streamlines
    directions = self.direction_getter.initial_direction(s)
  File "dipy\reconst\peak_direction_getter.pyx", line 65, in dipy.reconst.peak_direction_getter.PeaksAndMetricsDirectionGetter.initial_direction
  File "dipy\reconst\peak_direction_getter.pyx", line 48, in dipy.reconst.peak_direction_getter.PeaksAndMetricsDirectionGetter._initialize
  File "stringsource", line 654, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: cannot expose native-only dtype 'g' in non-native byte order '<' via buffer interface
-------------------- >> begin captured stdout << ---------------------
50.0 0.0
--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
root: INFO: Loading c:\projects\dipy\dipy\data\files\small_64D.nii
root: INFO: Computing response function
root: INFO: Eigenvalues for the frf of the input data are :[ 0.002  0.     0.   ]
root: INFO: Ratio for smallest to largest eigen value is 0.15343858702763827
root: INFO: CSD computation started.
root: INFO: CSD computation completed.
root: INFO: Pam5 file saved in C:\Users\appveyor\AppData\Local\Temp\1\tmpv9h3mof3
root: INFO: Creating mask of C:\Users\appveyor\AppData\Local\Temp\1\tmpv9h3mof3\gfa.nii.gz
root: INFO: Mask saved at C:\Users\appveyor\AppData\Local\Temp\1\tmpv9h3mof3\mask.nii.gz
root: INFO: Deterministic tracking on C:\Users\appveyor\AppData\Local\Temp\1\tmpv9h3mof3\peaks.pam5
root: INFO: classifier done
root: INFO: seeds done
root: INFO: LocalTracking initiated
--------------------- >> end captured logging << ---------------------
----------------------------------------------------------------------
```

IIUC, this is only affecting the workflow. Anyone have any ideas?

**Comment by skoudoro** [comment]
fix by #1899, I think. Closing for the moment. We can reopen it if this error reappears

**Comment by arokem** [comment]
Looks like this one has reared its ugly head again. See this failure https://ci.appveyor.com/project/skoudoro/dipy-5dd9b/builds/26873859/job/ciqcmaxv7ooiglnc 
(appears on the unrelated #1948)

Reopening...

**Comment by jhlegarreta** [comment]
:confused: 
https://docs.scipy.org/doc/numpy-1.13.0/user/basics.byteswapping.html
is may be relevant?

**Comment by skoudoro** [comment]
This error disappears again... I'm closing it,  until the next time...
