### ISSUE TITLE
Using the tutorial on Euler method on my data

### ISSUE THREAD

**Issue by alecrimi** [dipy/dipy#2034]
## Description
Hi I am getting a weird error I cannot debug when I am running the streamline generator. What I m doing is simply using your tutorial on Eu method but with my personal data. I am using Dipy 1.0.0 and Python3.6 .

this is the full list of the error:
```python
Traceback (most recent call last):
  File "tracking_introduction_eudx.py", line 167, in <module>
    streamlines = Streamlines(streamlines_generator)
  File "/home/alecrimi/.local/lib/python3.6/site-packages/nibabel/streamlines/array_sequence.py", line 135, in __init__
    self.extend(iterable)
  File "/home/alecrimi/.local/lib/python3.6/site-packages/nibabel/streamlines/array_sequence.py", line 315, in extend
    for e in elements:
  File "/home/alecrimi/.local/lib/python3.6/site-packages/dipy/tracking/utils.py", line 880, in transform_tracking_output
    for sl in streamlines:
  File "/home/alecrimi/.local/lib/python3.6/site-packages/dipy/tracking/local_tracking.py", line 120, in _generate_streamlines
    for s in self.seeds:
TypeError: 'int' object is not iterable
/home/alecrimi/.local/lib/python3.6/site-packages/matplotlib/backends/backend_gtk3.py:197: Warning: Source ID 8 was not found when attempting to remove it
  GLib.source_remove(self._idle_draw_id)
```

this is how I changed the code
```python 
interactive = False
import nibabel as nib
from dipy.core.gradients import gradient_table
from dipy.data import get_fnames
from dipy.io.gradients import read_bvals_bvecs
from dipy.io.image import load_nifti#, load_nifti_data

#hardi_fname, hardi_bval_fname, hardi_bvec_fname = get_fnames('stanford_hardi')
#label_fname = get_fnames('stanford_labels')
#data, affine, hardi_img = load_nifti(hardi_fname, return_img=True)
#labels = load_nifti_data(label_fname)
#bvals, bvecs = read_bvals_bvecs(hardi_bval_fname, hardi_bvec_fname)
#gtab = gradient_table(bvals, bvecs)

fimg = "DTICAP_bet.nii.gz"
img = nib.load(fimg)
data = img.get_data()
fbval = "DTICAP.bval"
fbvec = "DTICAP.bvec"
affine = img.affine

bvals, bvecs = read_bvals_bvecs(fbval, fbvec)
gtab = gradient_table(bvals, bvecs)

#white_matter = (labels == 1) | (labels == 2)

from dipy.reconst.csdeconv import auto_response
from dipy.reconst.shm import CsaOdfModel
from dipy.data import default_sphere
from dipy.direction import peaks_from_model

response, ratio = auto_response(gtab, data, roi_radius=10, fa_thr=0.7)
csa_model = CsaOdfModel(gtab, sh_order=6)
csa_peaks = peaks_from_model(csa_model, data, default_sphere,
                             relative_peak_threshold=.5,
                             min_separation_angle=25,
                             )
                             #mask=white_matter)

 
from dipy.tracking.stopping_criterion import ThresholdStoppingCriterion

stopping_criterion = ThresholdStoppingCriterion(csa_peaks.gfa, .25)
 

import matplotlib.pyplot as plt

sli = csa_peaks.gfa.shape[2] // 2
plt.figure('GFA')
plt.subplot(1, 2, 1).set_axis_off()
plt.imshow(csa_peaks.gfa[:, :, sli].T, cmap='gray', origin='lower')

plt.subplot(1, 2, 2).set_axis_off()
plt.imshow((csa_peaks.gfa[:, :, sli] > 0.25).T, cmap='gray', origin='lower')

plt.savefig('gfa_tracking_mask.png')
 
  
from dipy.tracking import utils

#seed_mask = (labels == 2)
#seeds = utils.seeds_from_mask(seed_mask, affine, density=[2, 2, 2])

from dipy.tracking.local_tracking import LocalTracking
from dipy.tracking.streamline import Streamlines

#Initialization of LocalTracking. The computation happens in the next step.
streamlines_generator = LocalTracking(csa_peaks, stopping_criterion, seeds=100000,
                                      affine=affine, step_size=.5)
#Generate streamlines object
streamlines = Streamlines(streamlines_generator)
 
from dipy.io.stateful_tractogram import Space, StatefulTractogram
from dipy.io.streamline import save_trk

sft = StatefulTractogram(streamlines, img, Space.RASMM)
save_trk(sft, "tractogram_EuDX.trk", streamlines)
```

**Comment by skoudoro** [comment]
Hi @alecrimi,

Your `seeds` are incorrect, it should be an array (N,3) and not an integer. This array is the region where you want to seeds. This is why it is failing. So you have to modify this line:
```python
#Initialization of LocalTracking. The computation happens in the next step.
streamlines_generator = LocalTracking(csa_peaks, stopping_criterion, seeds=100000,
                                      affine=affine, step_size=.5)
```

Hope it helps

**Comment by skoudoro** [comment]
### Small Notes

Need a PR to check this input and give a better message.

**Comment by skoudoro** [comment]
A solution to your problem would be to use `random_seeds_from_mask`:

```python
from dipy.tracking.utils import random_seeds_from_mask
# whole brain
mask = np.ones(data.shape)
# create seeds
seeds = random_seeds_from_mask(mask, affine, seeds_count=10000)
# then Initialization of LocalTracking. The computation happens in the next step.
streamlines_generator = LocalTracking(csa_peaks, stopping_criterion, seeds=seeds,
                                      affine=affine, step_size=.5)
```

**Comment by alecrimi** [comment]
Yes, I thought that was the way. Thanks

**Comment by alecrimi** [comment]
Solved!
A better way is to use a proper mask or to get it from the Otsu threshold:

from dipy.segment.mask import median_otsu
mask, S0_mask = median_otsu(data[:, :, :, 0])
# create seeds
seeds = random_seeds_from_mask(mask, affine, seeds_count=100)

**Comment by skoudoro** [comment]
Great ! I will keep this issue open as reminder to improve the error message
