### ISSUE TITLE
odf can not have nans

### ISSUE THREAD

**Issue by dPys** [dipy/dipy#2189]
In dipy 1.1.0, any time I run local tracking (deterministic or probabilistic) using a CSD reconstruction on certain datasets, I get the following error (takes different forms depending on the tractography):

directions = self.direction_getter.initial_direction(s)
  File "dipy/direction/closest_peak_direction_getter.pyx", line 78, in dipy.direction.closest_peak_direction_getter.BaseDirectionGetter.initial_direction
  File "dipy/direction/closest_peak_direction_getter.pyx", line 95, in dipy.direction.closest_peak_direction_getter.BaseDirectionGetter.initial_direction
  File "dipy/direction/closest_peak_direction_getter.pyx", line 76, in dipy.direction.closest_peak_direction_getter.BaseDirectionGetter._get_peak_directions
  File "/usr/local/anaconda3/lib/python3.7/site-packages/dipy/direction/peaks.py", line 128, in peak_directions
    values, indices = local_maxima(odf, sphere.edges)
  File "dipy/reconst/recspeed.pyx", line 244, in dipy.reconst.recspeed.local_maxima
ValueError: odf can not have nans

I'm running the following code to estimate csd:
```
    from dipy.reconst.csdeconv import (
        ConstrainedSphericalDeconvModel,
        recursive_response,
    )

    print("Fitting CSD model...")
    B0_mask_data = np.nan_to_num(np.asarray(
        nib.load(B0_mask).dataobj)).astype("bool")
    print("Reconstructing...")
    response = recursive_response(
        gtab,
        data,
        mask=B0_mask_data,
        sh_order=sh_order,
        peak_thr=0.01,
        init_fa=0.08,
        init_trace=0.0021,
        iter=8,
        convergence=0.001,
        parallel=False,
    )
    print("CSD Reponse: " + str(response))
    model = ConstrainedSphericalDeconvModel(gtab, response, sh_order=sh_order)
    csd_mod = model.fit(data, B0_mask_data).shm_coeff
```

Is this coming from my recursive response parameters? Any idea what I might be missing? All other types of reconstruction seem to do fine for tractography on the same data...

@ShreyasFadnavis @Garyfallidis @arokem

**Comment by arokem** [comment]
Do you have an example of the data from a voxel where this happens? And
bvals/bvecs

**Comment by dPys** [comment]
Thanks @arokem for looking into this!

Here's some data: https://drive.google.com/file/d/1vDatKTGKIiYcmVN_y27s7PYVSNw5gGg0/view?usp=sharing

And here's some code to reproduce the error exactly:

```
import os
import numpy as np
import nibabel as nib
import os.path as op
from dipy.io import load_pickle
from dipy.data import get_sphere
from dipy.reconst.csdeconv import ConstrainedSphericalDeconvModel, recursive_response
from dipy.direction import DeterministicMaximumDirectionGetter
from dipy.tracking import utils
from dipy.tracking.local_tracking import LocalTracking
from dipy.tracking.stopping_criterion import BinaryStoppingCriterion

dwi_file = '/Users/derekpisner/Desktop/sample_data/dwi.nii.gz'
wm_gm_int_path = '/Users/derekpisner/Desktop/sample_data/DesikanKlein2012_dwi_track_wmgm_int.nii.gz'
wm_mask = '/Users/derekpisner/Desktop/sample_data/t1w_wm_in_dwi_bin.nii.gz'
B0_mask = '/Users/derekpisner/Desktop/sample_data/mean_B0_bet_mask.nii.gz'
gtab_file = '/Users/derekpisner/Desktop/sample_data/gtab.pkl'


gtab = load_pickle(gtab_file)
# Load diffusion data
dwi_img = nib.load(dwi_file)
dwi_data = dwi_img.get_fdata()

# Load wm-gm seeding mask
wm_gm_int = nib.load(wm_gm_int_path).get_fdata()

B0_mask_data = np.nan_to_num(np.asarray(nib.load(B0_mask).dataobj)).astype("bool")
response = recursive_response(
         gtab,
         dwi_data,
         mask=B0_mask_data,
         sh_order=8,
         peak_thr=0.01,
         init_fa=0.08,
         init_trace=0.0021,
         iter=8,
         convergence=0.001,
         parallel=False)

model = ConstrainedSphericalDeconvModel(gtab, response, sh_order=8)
csd_mod = model.fit(dwi_data, B0_mask_data).shm_coeff

dg = DeterministicMaximumDirectionGetter.from_shcoeff(
                    csd_mod,
                    max_angle=30,
                    sphere=get_sphere('symmetric724'),
                    min_separation_angle=20)

seeds = utils.random_seeds_from_mask(
                    wm_gm_int > 0,
                    seeds_count=500,
                    seed_count_per_voxel=False,
                    affine=np.eye(4))

streamline_generator = LocalTracking(
                        dg,
                        BinaryStoppingCriterion(nib.load(wm_mask).get_fdata()),
                        seeds,
                        np.eye(4),
                        max_cross=2,
                        maxlen=1000,
                        step_size=0.2,
                        fixedstep=False,
                        return_all=True,
                    )
list(streamline_generator)
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-32-451c998beeb0> in <module>
     10                         return_all=True,
     11                     )
---> 12 list(streamline_generator)

/usr/local/anaconda3/lib/python3.7/site-packages/dipy/tracking/utils.py in transform_tracking_output(tracking_output, affine, save_seeds)
    878             yield np.dot(sl, lin_T) + offset, np.dot(seed, lin_T) + offset
    879     else:
--> 880         for sl in streamlines:
    881             yield np.dot(sl, lin_T) + offset
    882 

/usr/local/anaconda3/lib/python3.7/site-packages/dipy/tracking/local_tracking.py in _generate_streamlines(self)
    126                 random.seed(s_random_seed)
    127                 np.random.seed(s_random_seed)
--> 128             directions = self.direction_getter.initial_direction(s)
    129             if directions.size == 0 and self.return_all:
    130                 # only the seed position

dipy/direction/closest_peak_direction_getter.pyx in dipy.direction.closest_peak_direction_getter.BaseDirectionGetter.initial_direction()

dipy/direction/closest_peak_direction_getter.pyx in dipy.direction.closest_peak_direction_getter.BaseDirectionGetter.initial_direction()

dipy/direction/closest_peak_direction_getter.pyx in dipy.direction.closest_peak_direction_getter.BaseDirectionGetter._get_peak_directions()

/usr/local/anaconda3/lib/python3.7/site-packages/dipy/direction/peaks.py in peak_directions(odf, sphere, relative_peak_threshold, min_separation_angle)
    126 
    127     """
--> 128     values, indices = local_maxima(odf, sphere.edges)
    129 
    130     # If there is only one peak return

dipy/reconst/recspeed.pyx in dipy.reconst.recspeed.local_maxima()

ValueError: odf can not have nans

**Comment by dPys** [comment]
And here's the actual bvals/bvecs/metadata just in case: 


[metadata.zip](https://github.com/dipy/dipy/files/4867931/metadata.zip)

**Comment by dPys** [comment]
My guess is that it is that the b-value distribution of the data is not compatible with CSD. That being said, it might help to add a user-error to csd reconst when the gtab may not be compatible? Not sure what the right heuristic for determining that would be, though.

**Comment by arokem** [comment]
Hey! At least in many (all?) cases this happens in voxels that have
physically implausible signals in them.

Running:

```
idx = np.where(np.isnan(csd_mod))
nan_data = dwi_data[idx[0], idx[1], idx[2]]
nan_b0_data = np.mean(nan_data[:, gtab.b0s_mask], -1)
nan_dw_data = nan_data[:, ~gtab.b0s_mask]
diff = nan_b0_data[:, None] - dw_nan_data
```

You'll see that:

```
ipdb> nan_data[0]

array([52.57228701, 30.25594908, 18.21773651, 17.82880946, 24.74792828,
       18.68697137, 49.59169175, 42.75233528, 31.57341595, 18.01773805,
       11.85152257, 51.23931922, 36.76786744, 39.53462136, 26.40443661,
       29.21661914, 24.71854313, 31.10636292, 30.2365684 , 20.99611108,
       11.16897454, 28.66371041, 26.46036556, 19.94461119, 13.13297412,
       12.9523578 ])
```
So:

```
ipdb> nan_b0_data[0]     # The average of the first and second signals in
this voxel
41.41411804403951
```

Thus, the mean b0 signal is smaller than some of the diffusion-weighted
signals. Indeed:

```
ipdb> diff[0]

array([23.19638153, 23.58530858, 16.66618976, 22.72714668, -8.1775737 ,
       -1.33821723,  9.8407021 , 23.39637999, 29.56259548, -9.82520118,
        4.6462506 ,  1.87949668, 15.00968143, 12.1974989 , 16.69557491,
       10.30775513, 11.17754964, 20.41800697, 30.2451435 , 12.75040763,
       14.95375248, 21.46950685, 28.28114393, 28.46176025])
```
Negative numbers point to the diffusion-weighted signals that are larger
than the mean b0 signal in this voxel, which is not physically plausible.

Would it be helpful for us to raise a warning/error when aphysical signals
such as this are passed into models for fitting?

**Comment by dPys** [comment]
Thank you for this incredibly thorough explanation @arokem !! So helpful.

I think adding such a warning/error would be helpful. I'd be happy to PR it?

**Comment by arokem** [comment]
Yeah - that would be cool. I think that the best would be to raise a warning with the voxel coordinates in it when hitting a nan odf. We get these kinds of issues/messages often and it would be really helpful for diagnosis/triage if we could ask people to do something like:  

```
print(data[i,j,k])
print(gtab.bvals)
```

**Comment by dPys** [comment]
Hmm, maybe something along these lines?
```
def odf_plausibility_check(odf, dwi_data, gtab):
    import numpy as np
    import nibabel as nib
    idx = np.where(np.isnan(odf))
    if len(idx) > 0:
        i, j, k = idx[0], idx[1], idx[2]
        nan_data = dwi_data[i, j, k]
        diff = np.mean(nan_data[:, gtab.b0s_mask], -1)[:, None] - nan_data[:, ~gtab.b0s_mask]
        if (diff<0).any():
            idxs_neg = np.where(diff<0)[0]
            out_coords = set(list(zip(i, j, k)))
            raise ValueError(f"Implausible signals detected at {len(out_coords)} voxels\nB-values: {gtab.bvals}")
        else:
            raise ValueError(f"{len(idx)} NaN\'s detected in ODF, but signals appear plausible\nB-values: {gtab.bvals}")
    else:
        return
```

...if so, where might be the best home for it (e.g. dipy/reconst/odf.py, dipy/reconst/utils.py)? and any specific preference for where it would get applied?

**Comment by pfdamasceno** [comment]
hi @arokem and @dPys, 

We're running into this issue as well. From the explanations above, it's not clear to me whether there's a "fix" for the implausible signals or whether it means "bad input data" that should not be trusted... 

Thanks. cc @axiezai

**Comment by arokem** [comment]
Things to do (in the order I would do them): 

1.  Denoise the data (e.g., using patch2self).
2. Ignore the voxels. This is only a good solution if these voxels are not necessary for your analysis. But sometimes these voxels are rare, and there are enough other voxels to overcome this.
3. Impute the data: if you really need to analyze these voxels, you can consider imputation. This would mean that you would need to identify that this is happening and then use a model that ignores just the aphysical directions in that voxel and uses to the other directions.

**Comment by dPys** [comment]
+1 for @arokem 's suggestions. 

Also, are you including a brain mask ( and/or masking the 4d series) before fitting the odf? the most common scenario where I've encountered this error is when the brain mask isn't a snug fit, and near-zero voxels just outside of the skull "leak" into the reconstruction.
