### ISSUE TITLE
error performing cross-validation on diffusion HCP data

### ISSUE THREAD

**Issue by rosella1234** [dipy/dipy#2391]
When trying to apply cross-validation for dki model on 7T adult HCP data the following error arises:
```python
base) synapsi@charlie:/media/synapsi/dkeTest/new_version/code$ python goodness_of_fit.py
/home/synapsi/anaconda3/lib/python3.8/site-packages/dipy/core/gradients.py:295: UserWarning: b0_threshold (value: 50) is too low, increase your              b0_threshold. It should be higher than the lowest b0 value              (55.0).
  warn("b0_threshold (value: {0}) is too low, increase your \
Data & Mask Loaded!
Traceback (most recent call last):
  File "goodness_of_fit.py", line 21, in <module>
    dki_cc = xval.kfold_xval(dki_model, cc_vox, 2)
  File "/home/synapsi/anaconda3/lib/python3.8/site-packages/dipy/reconst/cross_validation.py", line 107, in kfold_xval
    raise ValueError(msg)
ValueError: np.mod(143, 2) is 1
```
Please find attached the code I used to do it 
```python
import numpy as np
np.random.seed(2014)
import matplotlib.pyplot as plt

import dipy.data as dpd
import dipy.reconst.cross_validation as xval
import dipy.reconst.dki as dki
import scipy.stats as stats
from dipy.core.gradients import gradient_table
from dipy.io.image import load_nifti
from dipy.io.gradients import read_bvals_bvecs
from dipy.io.image import save_nifti 
data, affine= load_nifti('/media/synapsi/dkeTest/new_version/100610/Diffusion_7T/denoised_patch2self.nii.gz')
bvals, bvecs=read_bvals_bvecs('/media/synapsi/dkeTest/new_version/100610/Diffusion_7T/bvals', '/media/synapsi/dkeTest/new_version/100610/Diffusion_7T/bvecs')
gtab=gradient_table(bvals, bvecs)
mask, affine= load_nifti('/media/synapsi/dkeTest/new_version/100610/Diffusion_7T/nodif_brain_mask.nii.gz')
print('Data & Mask Loaded!')
cc_vox = data[86, 115, 91]
#cso_vox = data[30, 76, 38]
dki_model = dki.DiffusionKurtosisModel(gtab)
dki_cc = xval.kfold_xval(dki_model, cc_vox, 2)
#dki_cso = xval.kfold_xval(dki_model, cso_vox, 2)
fig, ax = plt.subplots(1, 2)
fig.set_size_inches([12, 6])
ax[0].plot(cc_vox[gtab.b0s_mask == 0], dki_cc[gtab.b0s_mask == 0], 'o', color='b', label='DKI in CC')
#ax[1].plot(cso_vox[gtab.b0s_mask == 0], dki_cso[gtab.b0s_mask == 0], 'o',
           #color='b', label='DTI in CSO')
ax[0].legend(loc='upper left')
#ax[1].legend(loc='upper left')
for this_ax in ax:
    this_ax.set_xlabel('Data (relative to S0)')
    this_ax.set_ylabel('Model prediction (relative to S0)')
fig.savefig("model_predictions.png")

cc_dki_r2 = stats.pearsonr(cc_vox[gtab.b0s_mask == 0],
                           dki_cc[gtab.b0s_mask == 0])[0]**2
#cso_dki_r2 = stats.pearsonr(cso_vox[gtab.b0s_mask == 0],
                           # dki_cso[gtab.b0s_mask == 0])[0]**2


print("Corpus callosum\n"
      "DkI R2 : %s\n"
            "\n"
       % (cc_dki_r2))
```

```

**Comment by pjsjongsung** [comment]
the kfold_xval function should have a fold value that can equally divide the data. Right now, the error means that the data size is 143, but the fold is 2, so the dataset cannot be evenly split. A simple solution would be choosing a different fold value or using a sub part of the data.

Also, the code is not printing all the error message it is intended to. Line 106 of reconst/cross_validation.py should be msg += ~ instead of msg = .

**Comment by rosella1234** [comment]
I tried with a volume which is 145 x 174 x 145 x 288 and another error appears:

  _```
File "goodness_of_fit.py", line 19, in <module>
    dki_cc = xval.kfold_xval(dki_model, cc_vox, 2)
  File "/home/rosella/anaconda3/lib/python3.8/site-packages/dipy/reconst/cross_validation.py", line 100, in kfold_xval
    data_b = data[..., ~gtab.b0s_mask]
IndexError: invalid index to scalar variable.
```_

**Comment by arokem** [comment]
What is the shape of the variable `cc_vox` when it goes into the
`kfold_xval` function? Looks like maybe it's a scalar at that point.

**Comment by rosella1234** [comment]
Yes,
thank you. I solved my issue.
rosella
