### ISSUE TITLE
AffineMap.transform with option: interpolation='nearest' returns: "TypeError: No matching signature found"

### ISSUE THREAD

**Issue by amwink** [dipy/dipy#2414]
My script uses `dipy` to compute an affine transform to register a T1-weighted MR image to the T1 MNI template. The result is an AffineMap object.

This object is used to resample the MR image itself, with the line `resampled = final.transform ( mri )`; as copied from the registration example in the documentation. This uses linear interpolation and works fine, also if I add the option `interpolation = 'linear'`.

However when I use the transform on an atlas, whose labels cannot be interpolated, the command `resampled = final.transform ( atl, interpolation='nearest' )` makes the program exit with error message `TypeError: No matching signature found`.

The script that I use is attached. The function `gm_network()` (line 87) computes a grey matter network using Betty Tijms' method [1], which starts by rigid-registering the (grey matter density map of) an MR image to the MNI template. This is done in lines 106-167, which follows the recipe of https://dipy.org/documentation/1.4.0./examples_built/affine_registration_3d -- start with aligning centres of gravity, then allow translations, then also allow rotations. The resulting `AffineMap` object can also be written to / read from file (line 176).

The `AffineMap` object final contains the mapping of the MR to MNI space. The lines that produce the error are the ones that apply the mapping to the grey matter density map and the native-space atlas (188-195):

            # transform the grey matter data instead ofthe MRI itself       
            if not (  ( os.path.isfile ( new_gmfilename ) ) or ( os.path.islink ( new_gmfilename ) )  ):             
                resampled = final.transform ( grey );
                save_nifti ( new_gmfilename, resampled, static_affine );
            # transform the native-space atlas
            if not (  ( os.path.isfile ( new_atfilename ) ) or ( os.path.islink ( new_atfilename ) )  ):
                resampled = final.transform (  atl, 'nearest' );
                save_nifti ( new_atfilename, resampled, static_affine );

The line that uses 'nearest' causes it to stop, and gives this error:

    processing MR scan and GM density map with atlas
          /radshare/EPAD/analyses/multiNET/data/010EPAD00001_1/T1.nii
          /radshare/EPAD/analyses/multiNET/data/010EPAD00001_1/c1T1.nii
          /radshare/EPAD/analyses/multiNET/data/010EPAD00001_1/nativespace_DesKil.nii.gz
    file /radshare/EPAD/analyses/multiNET/data/010EPAD00001_1/c1T1_mni.nii or /radshare/EPAD/analyses/multiNET/data/010EPAD00001_1/nativespace_DesKil_mni.nii.gz does not exist
    performing registration to MNI ... 
    Traceback (most recent call last):
      File "gmnetwork.py", line 512, in <module> main()
      File "gmnetwork.py", line 72, in main
        obs_ran_net, net_file_name = gm_network ( mr, gm, at, mni_t1_template );
      File "gmnetwork.py", line 193, in gm_network
        resampled = final.transform (  atl, 'nearest' );
      File "/s4ever/radG/home_ubu1804/l.lorenzini/.local/lib/python3.7/site-packages/dipy/utils/deprecator.py", line 406, in wrapper
        return function(*args, **kwargs)
      File "/s4ever/radG/home_ubu1804/l.lorenzini/.local/lib/python3.7/site-packages/dipy/align/imaffine.py", line 414, in transform
        apply_inverse=False)
      File "/s4ever/radG/home_ubu1804/l.lorenzini/.local/lib/python3.7/site-packages/dipy/utils/deprecator.py", line 406, in wrapper
        return function(*args, **kwargs)
      File "/s4ever/radG/home_ubu1804/l.lorenzini/.local/lib/python3.7/site-packages/dipy/align/imaffine.py", line 363, in _apply_transform
        comp)
      File "dipy/align/vector_fields.pyx", line 1514, in dipy.align.vector_fields.__pyx_fused_cpdef
    TypeError: No matching signature found

We're running this on Ubuntu 18.04, Could be any type of Linux I'm sure, python 3.7 and dipy 1.4.

The error message suggests that there is a type conflict, is what I can find in general (outside of `dypi`)?

But the same command with a different interpolation parameter, or without interpolation parameters, works fine. In those situations I would say the same variables and types are used.

Happy to provide example MR images if required, preferably not publicly shared.

bw
Alle Meije

[1]  "Similarity-Based Extraction of Individual Networks from Gray Matter MRI Scans", BM Tijms et al. CerCor 22:1530
https://academic.oup.com/cercor/article/22/7/1530/291059

[gmnetwork.py.gz](https://github.com/dipy/dipy/files/6716625/gmnetwork.py.gz)

**Comment by amwink** [comment]
Update on this: I found a problem with my images: the atlas that was resampled was in neurological orientation, while the MRI-based images were both in radiological orientation. Because the voxel data were also flipped, this was not visible in the (NIfTI q/s-form-aware) viewer. After all the images were completely unrelated, so flipped orientations are not necessarily a problem.

Long story short: after making sure the q/s-forms of the atlas were the same as the MRI inputs and LR-flipping the voxel data, Both transforms work and the registered images look as they should in MNI space.

Not sure about whether to close the issue or not: if I understand correctly then `transform ( moving );`, `transform ( moving, interpolation = 'linear' );` and `transform ( moving, interpolation = 'nearest' );` should either all work (with proper images) or not work (otherwise), which does not seem to be the case.
