### ISSUE TITLE
Horizon error - disk position outside the slider line

### ISSUE THREAD

**Issue by Garyfallidis** [dipy/dipy#2441]
## Description

Master version of dipy_horizon (or viz.app.horizon) has issue when loading 4D images. 
For example, when I loaded the CFIN dwi image that we share with our users I got the following error.

```
ValueError: Disk position outside the slider line
Traceback (most recent call last):
  File "/home/elef/Devel/fury/fury/interactor.py", line 385, in _callback
    callback(self, prop, *args)
  File "/home/elef/Devel/fury/fury/ui.py", line 373, in mouse_move_callback
    self.on_left_mouse_button_dragged(i_ren, obj, self)
  File "/home/elef/Devel/fury/fury/ui.py", line 2204, in handle_move_callback
    self.set_position(position)
  File "/home/elef/Devel/fury/fury/ui.py", line 2113, in set_position
    self.update()  # Update information.
  File "/home/elef/Devel/fury/fury/ui.py", line 2149, in update
    raise ValueError("Disk position outside the slider line")
ValueError: Disk position outside the slider line
```

**Comment by Garyfallidis** [comment]
Certainly
```
 fury.get_info()
{'fury_version': '0.7.0.post209.dev0+geb85624',
 'commit_hash': 'eb85624ad432dded23733f335a57c684c6d765e6',
 'sys_version': '3.8.5 (default, Sep  4 2020, 07:30:14) \n[GCC 7.3.0]',
 'sys_platform': 'linux',
 'numpy_version': '1.19.2',
 'scipy_version': '1.5.2',
 'vtk_version': '9.0.3',
 'matplotlib_version': '3.3.4',
 'dipy_version': '1.5.0dev'}
```

**Comment by Garyfallidis** [comment]
I am worried that this maybe a UI issue in FURY. We need to fix this asap.

**Comment by Garyfallidis** [comment]
Something that was recently introduced.
