### ISSUE TITLE
ValueError while using register_dwi_series on a 4D dwi scan/

### ISSUE THREAD

**Issue by HilaGast** [dipy/dipy#2571]
Hi All,
I'm trying to register each bval volume in a 4D diffusion scan to the average of b0 volumes. I'm using register_dwi_series to do so with my scan as data, and 0 as b0 ref (using the default pipeline provided by the function). The function returns the following error:

_Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\HilaG\miniconda3\envs\LabPy\lib\site-packages\dipy\align\_public.py", line 775, in register_dwi_series
    series_arr = np.concatenate([ref_data, moving_data], -1)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 4 dimension(s)_

Any ideas what went wrong?

Thanks, Hila

Technical details:
_Windows-10-10.0.19041-SP0
Python 3.7.7
DiPy 1.4.0
NumPy 1.20.0, SciPy 1.7.3, Nibabel 3.1.0, H5py 2.10.0, Cvxpy 1.1.11, fury 0.6.0_

**Comment by arokem** [comment]
Thanks for reporting this. Can you say a bit more about your data? How many
volumes does the data have? How many b=0 volumes?

**Comment by HilaGast** [comment]
Sure, thanks for your willing to help.

The data is multi shell dwi (b=0, 1000, 2000 & 3000) - 288 volumes in total, among which 18 b=0 volumes - from the HCP database.

**Comment by arokem** [comment]
This does seem like a potential bug, but another question is whether this is necessary in this case. I believe that you can get HCP data that has already been preprocessed from the HCP database, so additional registration is not needed.

**Comment by HilaGast** [comment]
You're absolutely right about HCP data, but I'm just using it as an example for our own scans (in which the registration also fails). My guess is that it fails for the same reason (the details aren't identical, but they resemble quite a bit).

**Comment by arokem** [comment]
Yes. You're probably right. I'll look into this.
