### ISSUE TITLE
DIPY compilation fails with the last release of cython (0.29.29)

### ISSUE THREAD

**Issue by skoudoro** [dipy/dipy#2594]
> Avoid acquiring the GIL at the end of nogil functions. This change was backported in order to avoid generating wrong C code that would trigger C compiler warnings with tracing support enabled

This new cython feature might have an impact on our current code. We need to introspect.  see below:

cython 0.29.29 release notes: https://cython.readthedocs.io/en/latest/src/changes.html#id27

the current error:
```python
Installing collected packages: dipy
  Attempting uninstall: dipy
    Found existing installation: dipy 1.6.0.dev0
    Uninstalling dipy-1.6.0.dev0:
      Successfully uninstalled dipy-1.6.0.dev0
  Running setup.py develop for dipy
    ERROR: Command errored out with exit status 1:
     command: /Users/koudoro/miniconda3/envs/dipy-env-38/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/koudoro/Software/dipy/setup.py'"'"'; __file__='"'"'/Users/koudoro/Software/dipy/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/koudoro/Software/dipy/
    Complete output (112 lines):
    running develop
    running egg_info
    writing dipy.egg-info/PKG-INFO
    writing dependency_links to dipy.egg-info/dependency_links.txt
    writing requirements to dipy.egg-info/requires.txt
    writing top-level names to dipy.egg-info/top_level.txt
    reading manifest file 'dipy.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    /Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/setuptools/dist.py:502: UserWarning: Normalizing '1.6.0dev0' to '1.6.0.dev0'
      warnings.warn(tmpl.format(**locals()))
    /Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    warning: no files found matching 'TODO'
    adding license file 'LICENSE'
    running build_ext
    cythoning dipy/core/interpolation.pyx to dipy/core/interpolation.c
    cythoning dipy/direction/pmf.pyx to dipy/direction/pmf.c
    cythoning dipy/direction/probabilistic_direction_getter.pyx to dipy/direction/probabilistic_direction_getter.c
    cythoning dipy/direction/closest_peak_direction_getter.pyx to dipy/direction/closest_peak_direction_getter.c
    cythoning dipy/direction/bootstrap_direction_getter.pyx to dipy/direction/bootstrap_direction_getter.c
    cythoning dipy/reconst/eudx_direction_getter.pyx to dipy/reconst/eudx_direction_getter.c
    cythoning dipy/reconst/recspeed.pyx to dipy/reconst/recspeed.c
    cythoning dipy/reconst/vec_val_sum.pyx to dipy/reconst/vec_val_sum.c
    cythoning dipy/reconst/quick_squash.pyx to dipy/reconst/quick_squash.c
    cythoning dipy/tracking/distances.pyx to dipy/tracking/distances.c
    cythoning dipy/tracking/streamlinespeed.pyx to dipy/tracking/streamlinespeed.c
    cythoning dipy/tracking/localtrack.pyx to dipy/tracking/localtrack.c
    cythoning dipy/tracking/direction_getter.pyx to dipy/tracking/direction_getter.c
    cythoning dipy/tracking/stopping_criterion.pyx to dipy/tracking/stopping_criterion.c
    cythoning dipy/tracking/vox2track.pyx to dipy/tracking/vox2track.c
    cythoning dipy/tracking/propspeed.pyx to dipy/tracking/propspeed.c
    cythoning dipy/tracking/fbcmeasures.pyx to dipy/tracking/fbcmeasures.c
    cythoning dipy/segment/cythonutils.pyx to dipy/segment/cythonutils.c
    cythoning dipy/segment/featurespeed.pyx to dipy/segment/featurespeed.c
    cythoning dipy/segment/metricspeed.pyx to dipy/segment/metricspeed.c
    cythoning dipy/segment/clusteringspeed.pyx to dipy/segment/clusteringspeed.c
    cythoning dipy/segment/clustering_algorithms.pyx to dipy/segment/clustering_algorithms.c
    cythoning dipy/segment/mrf.pyx to dipy/segment/mrf.c
    cythoning dipy/denoise/denspeed.pyx to dipy/denoise/denspeed.c
    cythoning dipy/denoise/pca_noise_estimate.pyx to dipy/denoise/pca_noise_estimate.c
    cythoning dipy/denoise/nlmeans_block.pyx to dipy/denoise/nlmeans_block.c
    cythoning dipy/denoise/enhancement_kernel.pyx to dipy/denoise/enhancement_kernel.c
    warning: dipy/denoise/pca_noise_estimate.pyx:77:49: the result of using negative indices inside of code sections marked as 'wraparound=False' is undefined
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/koudoro/Software/dipy/setup.py", line 245, in <module>
        main(**extra_setuptools_args)
      File "/Users/koudoro/Software/dipy/setup.py", line 177, in main
        setup(name=info.NAME,
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/Users/koudoro/Software/dipy/setup_helpers.py", line 364, in build_extensions
        build_ext_class.build_extensions(self)
      File "/Users/koudoro/Software/dipy/setup_helpers.py", line 201, in build_extensions
        build_ext_class.build_extensions(self)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
        ext.sources = self.cython_sources(ext.sources, ext)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 346, in cython_sources
        result = cython_compile(source, options=options,
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 778, in compile
        return compile_single(source, options, full_module_name)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 727, in compile_single
        return run_pipeline(source, options, full_module_name)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 515, in run_pipeline
        err, enddata = Pipeline.run_pipeline(pipeline, source)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 355, in run_pipeline
        data = run(phase, data)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 335, in run
        return phase(data)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/Pipeline.py", line 52, in generate_pyx_code_stage
        module_node.process_implementation(options, result)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/ModuleNode.py", line 143, in process_implementation
        self.generate_c_code(env, options, result)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/ModuleNode.py", line 385, in generate_c_code
        self.body.generate_function_definitions(env, code)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_function_definitions
        stat.generate_function_definitions(env, code)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_function_definitions
        stat.generate_function_definitions(env, code)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 4894, in generate_function_definitions
        self.body.generate_function_definitions(self.scope, code)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_function_definitions
        stat.generate_function_definitions(env, code)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 389, in generate_function_definitions
        self.body.generate_function_definitions(env, code)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 442, in generate_function_definitions
        stat.generate_function_definitions(env, code)
      File "/Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/Cython/Compiler/Nodes.py", line 2096, in generate_function_definitions
        assert gil_owned['error'] == gil_owned['success'], "%s != %s" % (gil_owned['error'], gil_owned['success'])
    AssertionError: True != False
    ----------------------------------------
  Rolling back uninstall of dipy
  Moving to /Users/koudoro/miniconda3/envs/dipy-env-38/lib/python3.8/site-packages/dipy.egg-link
   from /private/var/folders/sg/t9v29psx03q040gzmrzdppgr0000gn/T/pip-uninstall-5n361p87/dipy.egg-link
ERROR: Command errored out with exit status 1: /Users/koudoro/miniconda3/envs/dipy-env-38/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/koudoro/Software/dipy/setup.py'"'"'; __file__='"'"'/Users/koudoro/Software/dipy/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by skoudoro** [comment]
closing, it was a cython issue. fixed by 0.29.30. see cython release notes [here](https://cython.readthedocs.io/en/latest/src/changes.html#id27)

**Comment by arokem** [comment]
Do you plan to put in a PR to revert #2595 and/or pin >=0.29.30?

**Comment by skoudoro** [comment]
> Do you plan to put in a PR to revert https://github.com/dipy/dipy/pull/2595 and/or pin >=0.29.30?

Not really since I use `!=0.29.29`. I might just need to update the minimum requirements for CI
