### ISSUE TITLE
IVIM VarPro fitting error

### ISSUE THREAD

**Issue by jZhuoMRI** [dipy/dipy#2649]
## Description
I am trying to run the IVIM model fitting, and the 'VarPro' option gives the following error:

ivimmodel_vp = IvimModel(gtab, fit_method='VarPro')
ivimfit_vp = ivimmodel_vp.fit(data_slice)
  0%|          | 0/5400 [01:50<?, ?it/s]
Traceback (most recent call last):
  File "/Users/jzhuo/.conda/envs/PythonProjects/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Users/jzhuo/.conda/envs/PythonProjects/lib/python3.10/site-packages/dipy/reconst/multi_voxel.py", line 35, in new_fit
    fit_array[ijk] = single_voxel_fit(self, data[ijk])
  File "/Users/jzhuo/.conda/envs/PythonProjects/lib/python3.10/site-packages/dipy/reconst/ivim.py", line 609, in fit
    f = self.cvx_fit(data, phi)
  File "/Users/jzhuo/.conda/envs/PythonProjects/lib/python3.10/site-packages/dipy/reconst/ivim.py", line 731, in cvx_fit
    f = cvxpy.Variable(2)
  File "/Users/jzhuo/.conda/envs/PythonProjects/lib/python3.10/site-packages/dipy/utils/tripwire.py", line 50, in __getattr__
    raise TripWireError(self._msg)
dipy.utils.tripwire.TripWireError: We need package cvxpy for these functions, but ``import cvxpy`` raised an ImportError

### 
I have tried to install Cvxpy, here is the info:

import cvxpy; print("Cvxpy", cvxpy.__version__)
Cvxpy 1.2.1

But errors still exist. Any thoughts? Thank you very much!

**Comment by skoudoro** [comment]
Hi @jZhuoMRI,

it sounds like an environment issue. 

it is strange that it does not find `cvxpy` if you install it. 

I recommend you to book a spot during the DIPY office hours [here](https://docs.google.com/spreadsheets/d/1IVaixEbjKQqS2MrZHw1L2Gso8a0GannT19GwWYhwFc0/edit#gid=0),  you will share your screen and we will look into it together and the creator of 'VarPro'.
