### ISSUE TITLE
ValueError: slice step cannot be zero

### ISSUE THREAD

**Issue by alienx-zero** [dipy/dipy#2742]
I try to extract the connectivity in these sentence:
`M, grouping = utils.connectivity_matrix(cc_streamlines, affine, parcellation.astype(int),
                                        return_mapping=True,
                                        mapping_as_streamlines=True)`
However, it rise error:
Traceback (most recent call last):
  File "F:\OPT\research\fMRI\utils_for_all\structural_connectivity_extract.py", line 152, in <module>
    M, grouping = utils.connectivity_matrix(cc_streamlines, np.eye(4), parcellation.astype(int),

  File "d:\Users\99488\anaconda3\envs\torch1.10\lib\site-packages\dipy\tracking\utils.py", line 220, in connectivity_matrix
    endpoints = [sl[0::len(sl)-1] for sl in streamlines]

  File "d:\Users\99488\anaconda3\envs\torch1.10\lib\site-packages\dipy\tracking\utils.py", line 220, in <listcomp>
    endpoints = [sl[0::len(sl)-1] for sl in streamlines]

ValueError: slice step cannot be zero
I debug these issue and figure out that for some streamline only one list with 3  value. Always the streamline should be a batch of list of 3 value, right? Any idea how to solve it

**Comment by skoudoro** [comment]
Hi @alienx-zero,

it will be very hard or almost impossible to help if we do not know how you obtain and select your streamlines. 
In this specific case, what is `cc_streamlines`?  how do you obtain it? 

PS: Converting this issue to a discussion since it more an help requested than an issue in DIPY
