### ISSUE TITLE
Use for loop when `num_processes=1` in gibbs_removal()

### ISSUE THREAD

**Issue by tashrifbillah** [dipy/dipy#2757]
### Description

Our data is 4D (diffusion weighted). We split it to 3D and then run Gibb's unringing. As you know, Gibb's unringing is a slow process. It is done slice by slice. So we already multiprocess the processing along 4th dimension. Our scheme worked with v1.1.0 because it was for-looped:

https://github.com/dipy/dipy/blob/160b202e7cd0ed821e5e1bfc4cf14815700430f3/dipy/denoise/gibbs.py#L288-L294

But now in v1.16.0, you have multiprocessed it along 3rd dimension:

https://github.com/dipy/dipy/blob/3667150a2f3c0c976af1c4729498a43bbbe39206/dipy/denoise/gibbs.py#L329-L337

This means multiprocessing within multiprocessing. Python is not capable of handling that and so I believe it crashes. So I do not get any output for our scheme.

### Solution

The solution is to run a for-loop for `num_processes=1` and mutliprocess it for more. If you agree with my idea, I shall submit a PR. My idea won't affect user I/O.

cc @ShreyasFadnavis @yrathi

**Comment by tanishka321** [comment]
While nested multiprocessing can pose challenges, it's not inherently doomed to crash Python. However, to address the concerns raised in this issue and ensure compatibility with the current implementation, This PR can be considered

**Comment by pjsjongsung** [comment]
I can confirm that it is still an issue. See below for the error message `gibbs_removal` is throwing

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,  
  File "/nobackup/jp109/envs/boystown/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/nobackup/jp109/envs/boystown/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/nobackup/jp109/envs/boystown/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/nfs/nfs9/home/nobackup/jp109/boystown/boystown_pipeline.py", line 69, in <module>
    T1_bf = gibbs_removal(T1, num_processes=2)
  File "/nfs/nfs9/home/nobackup/jp109/repos/dipy_js/dipy/testing/decorators.py", line 208, in wrapper
    return convert_positional_to_keyword(func, args, kwargs)
  File "/nfs/nfs9/home/nobackup/jp109/repos/dipy_js/dipy/testing/decorators.py", line 189, in convert_positional_to_keyword
    return func(*args, **kwargs)
  File "/nfs/nfs9/home/nobackup/jp109/repos/dipy_js/dipy/denoise/gibbs.py", line 334, in gibbs_removal
    pool = mp.Pool(num_processes)
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/nobackup/jp109/envs/boystown/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''

RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

Both `num_processes=1 and 2` threw the same error.

**Comment by tashrifbillah** [comment]
> I can confirm that it is still an issue. 

Yes that is what I commented in the PR. Currently, we are supporting our group by downloading https://raw.githubusercontent.com/dipy/dipy/160b202e7cd0ed821e5e1bfc4cf14815700430f3/dipy/denoise/gibbs.py -- the older code. Thus, we are no longer dependent on dipy's code progress.

**Comment by arokem** [comment]
Could you please make a new pr based on #3111? IIUC there were still some issues in that pr that were not fully addressed so it was not ready to merge. But if you can address those we can move ahead with this.
