### ISSUE TITLE
Prerelease wheels not NumPy 2.0.0.dev compatible

### ISSUE THREAD

**Issue by larsoner** [dipy/dipy#2979]
## Description

Dipy prerelease wheels at https://pypi.anaconda.org/scipy-wheels-nightly/simple are not compatible with the NumPy 2.0 wheels at https://pypi.anaconda.org/scientific-python-nightly-wheels/simple, so downstream libs like MNE-Python have to choose which prerelease dependency to test against (or split into multiple runs).

## Way to reproduce
[If reporting a bug, please include the following important information:]
- [x] Code example

```
$ pip install --upgrade --pre --extra-index-url "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" "numpy>=2.0.0.dev0" --extra-index-url "https://pypi.anaconda.org/scipy-wheels-nightly/simple" dipy
...
Successfully installed dipy-1.8.0.dev0 numpy-2.0.0.dev0
$ python -c "import dipy.align"
```

<details>
<summary>Traceback</summary>

```
$ python -c "import dipy.align"

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0.dev0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled against NumPy 2.0.

If you are a user of the module, the easiest solution will be to
either downgrade NumPy or update the failing module (if available).

NOTE: When testing against pre-release versions of NumPy 2.0
or building nightly wheels for it, it is necessary to ensure
the NumPy pre-release is used at build time.
The main way to ensure this is using no build isolation
and installing dependencies manually with NumPy.
For cibuildwheel for example, this may be achieved by using
the flag to pip:
    CIBW_BUILD_FRONTEND: pip; args: --no-build-isolation
installing NumPy with:
    pip install --pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
in the `CIBW_BEFORE_BUILD` step.  Please compare with the
solutions e.g. in astropy or matplotlib for how to make this
conditional for nightly wheel builds using expressions.
If you do not worry about using pre-releases of all
dependencies, you can also use `--pre --extra-index-url` in the
build frontend (instead of build isolation).
This will become unnecessary as soon as NumPy 2.0 is released.

If your dependencies have the issue, check whether they
have nightly wheels build against NumPy 2.0.

pybind11 note: You may see this message if using pybind11,
this is not problematic at pre-release time
it indicates the need for a new pybind11 release.

Traceback (most recent call last):
  File "__init__.pxd", line 942, in numpy.import_array
RuntimeError: module compiled against ABI version 0x1000009 but this version of numpy is 0x2000000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/larsoner/python/virtualenvs/base/lib/python3.11/site-packages/dipy/align/__init__.py", line 27, in <module>
    from dipy.align._public import (syn_registration, register_dwi_to_template, # noqa
  File "/home/larsoner/python/virtualenvs/base/lib/python3.11/site-packages/dipy/align/_public.py", line 31, in <module>
    import dipy.core.gradients as dpg
  File "/home/larsoner/python/virtualenvs/base/lib/python3.11/site-packages/dipy/core/gradients.py", line 7, in <module>
    from dipy.io import gradients as io
  File "/home/larsoner/python/virtualenvs/base/lib/python3.11/site-packages/dipy/io/__init__.py", line 4, in <module>
    from .dpy import Dpy
  File "/home/larsoner/python/virtualenvs/base/lib/python3.11/site-packages/dipy/io/dpy.py", line 12, in <module>
    import h5py
  File "/home/larsoner/python/virtualenvs/base/lib/python3.11/site-packages/h5py/__init__.py", line 45, in <module>
    from ._conv import register_converters as _register_converters, \
  File "h5py/_conv.pyx", line 1, in init h5py._conv
  File "h5py/h5r.pyx", line 1, in init h5py.h5r
  File "h5py/h5p.pyx", line 1, in init h5py.h5p
  File "h5py/h5t.pyx", line 1, in init h5py.h5t
  File "h5py/utils.pyx", line 19, in init h5py.utils
  File "__init__.pxd", line 944, in numpy.import_array
ImportError: numpy.core.multiarray failed to import

```

</details>

- [x] Operating system and version (run `python -c "import platform; print(platform.platform())"`): Linux-6.5.0-13-generic-x86_64-with-glibc2.38
- [x] Python version (run `python -c "import sys; print("Python", sys.version)"`): 3.11.6
- [x] dipy version (run `python -c "import dipy; print(dipy.__version__)"`): 1.8.0.dev0
- [x] dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
    * import numpy; print("NumPy", numpy.__version__): 2.0.0.dev0+git20231124.94bc564

**Comment by skoudoro** [comment]
Thank you @larsoner,

so we need to update our CI which seems to failed. We use the pre-wheels as you can see here: https://github.com/dipy/dipy/actions/runs/6958505036/job/18933655838#step:6:64

However, it seems that a dependency uninstall numpy 2.0.0 and install Numpy 1.16.0.  Do you know how can I avoid this kind of behavior ? I would like to force the use of all pre-wheels.

**Comment by larsoner** [comment]
Looking at the traceback in the `details` fold above, NumPy gives some advice:
```
NOTE: When testing against pre-release versions of NumPy 2.0
or building nightly wheels for it, it is necessary to ensure
the NumPy pre-release is used at build time.
The main way to ensure this is using no build isolation
and installing dependencies manually with NumPy.
For cibuildwheel for example, this may be achieved by using
the flag to pip:
    CIBW_BUILD_FRONTEND: pip; args: --no-build-isolation
installing NumPy with:
    pip install --pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple
in the `CIBW_BEFORE_BUILD` step.  Please compare with the
solutions e.g. in astropy or matplotlib for how to make this
conditional for nightly wheel builds using expressions.
If you do not worry about using pre-releases of all
dependencies, you can also use `--pre --extra-index-url` in the
build frontend (instead of build isolation).
This will become unnecessary as soon as NumPy 2.0 is released.
```
I'm guessing the CIBW_BUILD_FRONTEND and `--no-build-isolation` stuff should help

**Comment by larsoner** [comment]
... in other words, when you go to build the wheels make sure you install `pip install --extra-index-url ... "numpy>=2.0.0.dev0" ...` or so (with appropriate URL and other deps listed) then when `pip` builds your wheels make sure it gets the `--no-build-isolation` flag.

If the `pip install` line fails it will tell you which dependency is pinning NumPy, if any. But if it's something like SciPy it should already get a 2.0-compat version installed from `scientific-python-nightly-wheels` as well

**Comment by skoudoro** [comment]
Hi @larsoner,

since `https://pypi.anaconda.org/scipy-wheels-nightly/simple` is deprecated, our nightly wheels will be in `https://pypi.anaconda.org/dipy/label/dev/simple`.  

They should be compatible with `Numpy 2.0.0.dev0` now. 

Please, feel free to reopen the issue if it is not working as expected. 

Thank you for the feedback.

**Comment by larsoner** [comment]
In MNE-Python I use the prelease wheels on scientific-python-nightly-wheels in this job (looks like it gets your wheels from 1 day ago):

https://github.com/mne-tools/mne-python/actions/runs/8422750814/job/23062783320?pr=12511#step:11:47

```
├☑ dipy                 1.10.0.dev0+229.0e1f9e8
```

We get an error. Locally I can replicate with:
```
$ python -m venv np2
$ source np2/bin/activate
$ (np2) $ pip install --upgrade --extra-index-url "https://pypi.anaconda.org/scientific-python-nightly-wheels/simple" "numpy>=2.1.0.dev0" "scikit-learn>=1.5.dev" "scipy>=1.13.dev" "numpy>=2.0.0.dev0" "dipy>=1.10.0.dev0"
$ python
>>> import dipy
>>> dipy.__version__
'1.10.0.dev0+229.0e1f9e8'
>>> dipy.__file__
'/home/larsoner/python/virtualenvs/np2/lib/python3.11/site-packages/dipy/__init__.py'
>>> from dipy.align.imaffine import AffineMap

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0.dev0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled against NumPy 2.0.

If you are a user of the module, the easiest solution will be to
either downgrade NumPy or update the failing module (if available).

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/home/larsoner/python/virtualenvs/np2/lib/python3.11/site-packages/dipy/align/__init__.py", line 26, in <module>
    from dipy.align._public import (syn_registration, register_dwi_to_template, # noqa
  File "/home/larsoner/python/virtualenvs/np2/lib/python3.11/site-packages/dipy/align/_public.py", line 15, in <module>
    from dipy.align.metrics import CCMetric, EMMetric, SSDMetric
  File "/home/larsoner/python/virtualenvs/np2/lib/python3.11/site-packages/dipy/align/metrics.py", line 7, in <module>
    from dipy.align import vector_fields as vfu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/larsoner/python/virtualenvs/np2/lib/python3.11/site-packages/dipy/align/__init__.py", line 26, in <module>
    from dipy.align._public import (syn_registration, register_dwi_to_template, # noqa
  File "/home/larsoner/python/virtualenvs/np2/lib/python3.11/site-packages/dipy/align/_public.py", line 15, in <module>
    from dipy.align.metrics import CCMetric, EMMetric, SSDMetric
  File "/home/larsoner/python/virtualenvs/np2/lib/python3.11/site-packages/dipy/align/metrics.py", line 7, in <module>
    from dipy.align import vector_fields as vfu
  File "vector_fields.pyx", line 1, in init dipy.align.vector_fields
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```
Is it possible you are not compiling your nightly wheels against 2.0?

**Comment by skoudoro** [comment]
> Is it possible you are not compiling your nightly wheels against 2.0?

Yes it is possible, I will look into it. Thank you for the feedback

**Comment by larsoner** [comment]
Already in progress in https://github.com/dipy/dipy/pull/3150 !
