### ISSUE TITLE
NumPy 2.0 incompatibility

### ISSUE THREAD

**Issue by drammock** [dipy/dipy#3265]
## Description
One of MNE-Python's CIs is failing due to a NumPy 2.0 incompatibility in DIPY. 

```
Traceback (most recent call last):
  File "/home/circleci/project/tutorials/inverse/50_beamformer_lcmv.py", line 316, in <module>
    morph = mne.compute_source_morph(
  File "<decorator-gen-489>", line 10, in compute_source_morph
  File "/home/circleci/project/mne/morph.py", line 262, in compute_source_morph
    shape, zooms, affine, pre_affine, sdr_morph = _compute_morph_sdr(
  File "/home/circleci/project/mne/morph.py", line 1147, in _compute_morph_sdr
    from dipy.align.imaffine import AffineMap
  File "/home/circleci/python_env/lib/python3.10/site-packages/dipy/align/__init__.py", line 26, in <module>
    from dipy.align._public import (syn_registration, register_dwi_to_template, # noqa
  File "/home/circleci/python_env/lib/python3.10/site-packages/dipy/align/_public.py", line 15, in <module>
    from dipy.align.metrics import CCMetric, EMMetric, SSDMetric
  File "/home/circleci/python_env/lib/python3.10/site-packages/dipy/align/metrics.py", line 7, in <module>
    from dipy.align import vector_fields as vfu
  File "vector_fields.pyx", line 1, in init dipy.align.vector_fields
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

That CI is running Ubuntu 22.04, Python 3.10, and

```
Package                       Version                Editable project location
----------------------------- ---------------------- -------------------------
cvxpy                         not installed
dipy                          1.9.0
fury                          not installed
h5py                          3.11.0
mne                           1.8.0.dev72+gc24702cb9 /home/circleci/project
nibabel                       5.2.1
numpy                         2.0.0
scipy                         1.13.1
```

To reproduce, create environment w/ the above deps, and run the tutorial file: https://mne.tools/dev/auto_tutorials/inverse/50_beamformer_lcmv.html

## Way to reproduce
- [x] Code example
- [x] Relevant images (if any)
- [x] Operating system and version (run `python -c "import platform; print(platform.platform())"`)
- [x] Python version (run `python -c "import sys; print('Python', sys.version)"`)
- [x] dipy version (run `python -c "import dipy; print(dipy.__version__)"`)
- [x] dependency version (numpy, scipy, nibabel, h5py, cvxpy, fury)
    * import numpy; print("NumPy", numpy.__version__)
    * import scipy; print("SciPy", scipy.__version__)
    * import nibabel; print("Nibabel", nibabel.__version__)
    * import h5py; print("H5py", h5py.__version__)
    * import cvxpy; print("Cvxpy", cvxpy.__version__)
    * import fury; print("fury", fury.__version__)

**Comment by larsoner** [comment]
We also see it in Windows 3.10:

https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=30412

```
Platform                Windows-10-10.0.20348-SP0
Python                  3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
...
├☑ numpy                2.0.0 (OpenBLAS 0.3.27 with 2 threads)
...
├☑ dipy                 1.9.0
...
```

**Comment by skoudoro** [comment]
Sorry for the late feedback.

We will work on it and cut a release ASAP

**Comment by Garyfallidis** [comment]
Nonetheless thank you for reporting @drammock !
