### ISSUE TITLE
dipy_buan_profiles CLI IndexError

### ISSUE THREAD

**Issue by marcjaskir** [dipy/dipy#3370]
## Description

Hello! I'm trying to use the dipy_buan_profiles CLI, but I can't seem to resolve the error below related to the stats.anatomical_measures function. The .nii.gz and .trk files all look reasonable and are organized according to the BUAN specifications. Any guidance would be appreciated!

## Way to reproduce

My call:

```
#!/bin/bash

sub=0490

sub_inputs_dir=/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/${sub}
outputs_dir=/home/mjaskir/projects/tractometry/outputs/${sub}/bundle_profiles

# Make outputs directory
if [[ ! -d ${outputs_dir} ]]; then
        mkdir -p ${outputs_dir}
fi

dipy_buan_profiles ${sub_inputs_dir}/bundles/ \
        ${sub_inputs_dir}/subjects/ \
        --out_dir ${outputs_dir}
```

Outputs:

```
INFO:group = control
INFO:['0505', '0600', '0602', '0603', '0604', '0615', '0682', '0683', '0815', '0816', '0817', '0818', '0819', '0820', '0826', '0827', '0830', '0833', '0854', '0884', '0887', '0894', '0911', '0912', '0913', '0919', '0927']
INFO:0505
INFO:/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505
['/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/AF_L.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/AF_R.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/CFPH_L.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/CFPH_R.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/CPH_L.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/CPH_R.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/CPHP_L.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/CPHP_R.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/CPO_L.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/CPO_R.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/F_L.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/F_R.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/ILF_L.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/ILF_R.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/UF_L.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/bundles/UF_R.trk']
['/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/AF_L_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/AF_R_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/CFPH_L_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/CFPH_R_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/CPHP_L_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/CPHP_R_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/CPH_L_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/CPH_R_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/CPO_L_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/CPO_R_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/F_L_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/F_R_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/ILF_L_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/ILF_R_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/UF_L_mni.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/rec_bundles/UF_R_mni.trk']
['/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/AF_L_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/AF_R_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/CFPH_L_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/CFPH_R_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/CPHP_L_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/CPHP_R_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/CPH_L_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/CPH_R_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/CPO_L_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/CPO_R_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/F_L_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/F_R_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/ILF_L_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/ILF_R_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/UF_L_native.trk', '/home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/org_bundles/UF_R_native.trk']
INFO:bm = AF_L
INFO:metric = /home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/anatomical_measures/icvf.nii.gz
INFO:bm = AF_L
INFO:metric = /home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/anatomical_measures/od.nii.gz
INFO:bm = AF_R
INFO:metric = /home/mjaskir/projects/tractometry/data/buan/inputs_single_patient/0490/subjects/control/0505/anatomical_measures/icvf.nii.gz
Traceback (most recent call last):
  File "/home/mjaskir/.conda/envs/dipy/bin/dipy_buan_profiles", line 10, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/mjaskir/.conda/envs/dipy/lib/python3.12/site-packages/dipy/workflows/cli.py", line 61, in run
    run_flow(getattr(mod, flow_name)())
  File "/home/mjaskir/.conda/envs/dipy/lib/python3.12/site-packages/dipy/workflows/flow_runner.py", line 88, in run_flow
    return flow.run(**args)
           ^^^^^^^^^^^^^^^^
  File "/home/mjaskir/.conda/envs/dipy/lib/python3.12/site-packages/dipy/workflows/stats.py", line 355, in run
    buan_bundle_profiles(model_bundle_folder, b, c, d, group_id,
  File "/home/mjaskir/.conda/envs/dipy/lib/python3.12/site-packages/dipy/workflows/stats.py", line 269, in buan_bundle_profiles
    anatomical_measures(transformed_orig_bundles, metric, dt, fm,
  File "/home/mjaskir/.conda/envs/dipy/lib/python3.12/site-packages/dipy/stats/analysis.py", line 91, in anatomical_measures
    dt["disk"].extend(ind[list(range(len(values)))]+1)
                      ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: index 94679 is out of bounds for axis 0 with size 94679
```

OS version: Linux-3.10.0-1160.119.1.el7.x86_64-x86_64-with-glibc2.17
Python version: Python 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0]
dipy version:  1.9.0
dependencies:
* NumPy 1.26.4
* SciPy 1.13.1
* Nibabel 5.2.1
* H5py 3.11.0
* Cvxpy 1.5.1
* fury 0.10.0

**Comment by marcjaskir** [comment]
Sharing the directory structure as well, if that's clearer and helpful:

```
.
├── bundles
│   ├── AF_L.trk
│   ├── AF_R.trk
│   ├── CFPH_L.trk
│   ├── CFPH_R.trk
│   ├── CPHP_L.trk
│   ├── CPHP_R.trk
│   ├── CPH_L.trk
│   ├── CPH_R.trk
│   ├── CPO_L.trk
│   ├── CPO_R.trk
│   ├── F_L.trk
│   ├── F_R.trk
│   ├── ILF_L.trk
│   ├── ILF_R.trk
│   ├── UF_L.trk
│   └── UF_R.trk
└── subjects
    ├── control
    │   ├── 0505
    │   │   ├── anatomical_measures
    │   │   │   ├── fa.nii.gz
    │   │   │   ├── icvf.nii.gz
    │   │   │   ├── isovf.nii.gz
    │   │   │   ├── md.nii.gz
    │   │   │   └── od.nii.gz
    │   │   ├── org_bundles
    │   │   │   ├── AF_L_native.trk
    │   │   │   ├── AF_R_native.trk
    │   │   │   ├── CFPH_L_native.trk
    │   │   │   ├── CFPH_R_native.trk
    │   │   │   ├── CPHP_L_native.trk
    │   │   │   ├── CPHP_R_native.trk
    │   │   │   ├── CPH_L_native.trk
    │   │   │   ├── CPH_R_native.trk
    │   │   │   ├── CPO_L_native.trk
    │   │   │   ├── CPO_R_native.trk
    │   │   │   ├── F_L_native.trk
    │   │   │   ├── F_R_native.trk
    │   │   │   ├── ILF_L_native.trk
    │   │   │   ├── ILF_R_native.trk
    │   │   │   ├── UF_L_native.trk
    │   │   │   └── UF_R_native.trk
    │   │   └── rec_bundles
    │   │       ├── AF_L_mni.trk
    │   │       ├── AF_R_mni.trk
    │   │       ├── CFPH_L_mni.trk
    │   │       ├── CFPH_R_mni.trk
    │   │       ├── CPHP_L_mni.trk
    │   │       ├── CPHP_R_mni.trk
    │   │       ├── CPH_L_mni.trk
    │   │       ├── CPH_R_mni.trk
    │   │       ├── CPO_L_mni.trk
    │   │       ├── CPO_R_mni.trk
    │   │       ├── F_L_mni.trk
    │   │       ├── F_R_mni.trk
    │   │       ├── ILF_L_mni.trk
    │   │       ├── ILF_R_mni.trk
    │   │       ├── UF_L_mni.trk
    │   │       └── UF_R_mni.trk

...

    └── patient
        └── 0490

...
```

**Comment by marcjaskir** [comment]
Resolved - this was a human error related to symlinking files to create the BUAN-compliant input directory. Sorry to bother!

**Comment by skoudoro** [comment]
Thank you for the feedback!
